### ISSUE TITLE
[UX] Spring Simulator - Text highlighting and cursor 

### ISSUE THREAD

**Issue by jmaicaaan** [cedmandocdoc/galaw#3]
While playing the spring, it always highlights the text and the cursor of the ball pink isn't in pointer effect. Should we consider not allowing to highlight the text while dragging the ball and updating the cursor of the mouse? 

![Jul-29-2020 21-37-19](https://user-images.githubusercontent.com/13105222/88807611-860d7900-d1e4-11ea-9bdf-a6bd8e9d7df1.gif)

**Comment by cedmandocdoc** [comment]
Hi @jmaicaaan, I agree, the highlight is kinda off. However, the [galaw-demos](https://github.com/cedmandocdoc/galaw-demos) repository is different on the galaw animation library. I've pushed a commit and deployed, check it out! Thank you for your time filing an issue, I will close this now, if there is still a bug about the highlighting reset please file it [here](https://github.com/cedmandocdoc/galaw-demos/issues), thank you again!
