### ISSUE TITLE
[UX] 3D Spring Card - Reset position/animation when user is outside the container/boundary

### ISSUE THREAD

**Issue by jmaicaaan** [cedmandocdoc/galaw#4]
When you hover the spring card, it shows the animation which is awesome! What do you think about resetting the position/animation of the card when the mouse is outside the container/boundary?

![Jul-29-2020 21-37-52-2](https://user-images.githubusercontent.com/13105222/88807988-e2709880-d1e4-11ea-952b-683f7ef8c98f.gif)

**Comment by cedmandocdoc** [comment]
Hi @jmaicaaan, yeah that would be great! However, the [galaw-demos](https://github.com/cedmandocdoc/galaw-demos) repository is different on the galaw animation library. I've pushed a commit and deployed, check it out! Thank you for your time filing an issue, I will close this now, if there is still a bug about the hover reset please file it [here](https://github.com/cedmandocdoc/galaw-demos/issues), thank you again!
